version: '3.3'

services:
  app:
     image: rust:1.19.0
     volumes:
     - .:/app/
     working_dir: /app/
     command: cargo run
     environment:
     - 'SLACK_WEBHOOKS=https://hooks.slack.com/services/'
  my-redis:
    image: redis:alpine
